### PR TITLE
Made the p.h1 an actual h1.h1

### PR DESCRIPTION
**Pull request by Shoom**
The pages were lacking a first level heading. The p element in the hero module with the .h1 class seemed quite suited for that task.
I assume every page should only have one hero module, right? (also I couldn't see a page that had multiple ones). Maybe there was a good reason for this?

### CODE REVIEW

**Comment by Shoom** [comment]
yeah… scrap that… there actually are multiple heroes per page… suppose you can throw the h2s out as well then :P

**Comment by marionebl** [comment]
Not so fast, let's solve this! 🚀 

The hero module could learn to render configurable headline tags.

**Comment by KnisterPeter** [comment]
But there is currently one point in this: The homepage does not have a real h1. Other pages meight tho.

**Comment by marionebl** [comment]
I think you **could** argue the first hero module has the highest weight with all other modules following suit on the same levels as h2

**Comment by Shoom** [comment]
resolve by #75

**Pull request closed without merging**
